name: Generate Documentation on GithubPages

on:
  push:
    branches:
      - dev
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}      
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
          cache: 'pip'      
      - run: |
          pip install mkdocs-material
          mkdocs gh-deploy --force
