name: Generate Documentation on GithubPages

on:
  push:
    branches:
      - dev
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
          cache: 'pip'
      - name: Install pre-requisite
        run: |
          sudo apt install gdb -y
          pip install --requirement docs/requirements.txt
      - name: Regenerate GEF API file
        run: |
          echo "$(pwd)/gef.py" > ~/.gdbinit
          bash scripts/generate-api-docs.sh
      - name: Build and publish the docs
        run: |
          git config --global user.name "hugsy"
          git config --global user.email "hugsy@users.noreply.github.com"
          mkdocs gh-deploy --force
